[riotapi]
[riotapi.host]
# This field may not in use
LARGE_REGION = ["AMERICAS", "ASIA", "EUROPE", "ESPORTS", "SEA"]
SMALL_REGION = ["BR1", "EUN1", "EUW1", "JP1", "KR", "LA1", "LA2", "NA1", "OC1", "PH2", "RU", "SG2", "TH2", "TR1", "TW2", "VN2"]

[riotapi.key]
APIKEY="RGAPI-567085ec-96e3-4892-b1f0-d828c3e686b2"
PARAM_NAME="api_key"
HEADER_NAME="X-Riot-Token"
PREFER_APPROACH="HEADER"

[riotapi.key.expiry_date]
# You can set either the token lifetime or program lifetime here as wished
YEAR=2024
MONTH=5
DAY=31
HOUR=8
MINUTE=41
SECOND=0
TIMEZONE='America/New_York'

[riotapi.limit]
[riotapi.limit.global]
[riotapi.limit.global.1]
MAX_REQUESTS = 20
REQUESTS_INTERVAL = 1

[riotapi.limit.global.2]
MAX_REQUESTS = 100
REQUESTS_INTERVAL = 120


[riotapi.httpx_timeout]
# ALL=30
CONNECT=30
READ=30
WRITE=30
POOL=30


[riotapi.user]
# PUUID="yAguDuygGSVyrXgyX0b04gcWweYxXyUuURwZI1p8RIuk-lc4iQV7VxL7h_hZK7mfQl4nBeqBPDXziA"
USERNAME="SlayerIchiruTake"
TAGLINE="5092"
REGION="VN2"
