[riotapi]


[riotapi.key]
APIKEY="RGAPI-5958ecf4-5357-42ba-a15f-f03fb41714bb"
QUERY_PARAM_NAME="api_key"
HEADER_NAME="X-Riot-Token"

[riotapi.key.expiry_date]
YEAR=2024
MONTH=5
DAY=2
HOUR=8
MINUTE=41
SECOND=0
TIMEZONE='America/New_York'

[riotapi.limit]
MAX_REQUESTS_PER_SECOND=20
# The number of requests per 2 minutes is 100 but we will use 50 to be safe.
MAX_REQUESTS_PER_MINUTE=50

[riotapi.user]
# PUUID="yAguDuygGSVyrXgyX0b04gcWweYxXyUuURwZI1p8RIuk-lc4iQV7VxL7h_hZK7mfQl4nBeqBPDXziA"
USERNAME="SlayerIchiruTake"
TAGLINE="5092"
REGION="VN2"
SUBREGION=["ASIA", "SEA"]
