[riotapi]

[riotapi.full.key]
# Development Key
APIKEY="RGAPI-711f241e-2bea-4b32-a7e2-ccb122fe2581"
PARAM_NAME="api_key"
HEADER_NAME="X-Riot-Token"
PREFER_APPROACH="HEADER"

[riotapi.full.speed.1]
SPEED=20
SECOND=1

[riotapi.full.speed.2]
SPEED=100
SECOND=120


[riotapi.lol.key]
APIKEY="RGAPI-711f241e-2bea-4b32-a7e2-ccb122fe2581"
PARAM_NAME="api_key"
HEADER_NAME="X-Riot-Token"
PREFER_APPROACH="HEADER"

[riotapi.lol.speed.1]
SPEED=20
SECOND=1

[riotapi.lol.speed.2]
SPEED=100
SECOND=120


[riotapi.lor.key]
APIKEY="RGAPI-711f241e-2bea-4b32-a7e2-ccb122fe2581"
PARAM_NAME="api_key"
HEADER_NAME="X-Riot-Token"
PREFER_APPROACH="HEADER"

[riotapi.lor.speed.1]
SPEED=20
SECOND=1

[riotapi.lor.speed.2]
SPEED=100
SECOND=120


[riotapi.tft.key]
APIKEY="RGAPI-711f241e-2bea-4b32-a7e2-ccb122fe2581"
PARAM_NAME="api_key"
HEADER_NAME="X-Riot-Token"
PREFER_APPROACH="HEADER"

[riotapi.tft.speed.1]
SPEED=20
SECOND=1

[riotapi.tft.speed.2]
SPEED=100
SECOND=120

[riotapi.val.key]
APIKEY="RGAPI-711f241e-2bea-4b32-a7e2-ccb122fe2581"
PARAM_NAME="api_key"
HEADER_NAME="X-Riot-Token"
PREFER_APPROACH="HEADER"

[riotapi.val.speed.1]
SPEED=20
SECOND=1

[riotapi.val.speed.2]
SPEED=100
SECOND=120


[riotapi.default]
# Default user
# PUUID="GG3JvY2K5hx6OKoy_f90Qyoh5mOLQVcmTc2nh0CFZroE6oZXUv33UQgR5H16cEz6pDByxH7nyCLWLQ"
# PUUID="yAguDuygGSVyrXgyX0b04gcWweYxXyUuURwZI1p8RIuk-lc4iQV7VxL7h_hZK7mfQl4nBeqBPDXziA"
# USERNAME="SlayerIchiruTake"
# TAGLINE="5092"
IGNORED="VN2"

