[riotapi]

[riotapi.default]
# The update mechanism will be triggered every 3 minutes
REFRESH_RATE=180
REGION="VN2"
CONTINENT="ASIA"
LOCALE="en_US"

[riotapi.default.httpx_timeout]
ALL=30
CONNECT=15
READ=15
WRITE=15
POOL=15

[riotapi.expiry_date]
# You can set either the token lifetime or program lifetime here as wished
# Note that when you have updates the value here, to make it effective, you must trigger one request to the RiotAPI
YEAR=2024
MONTH=12
DAY=31
HOUR=8
MINUTE=41
SECOND=0
TIMEZONE='America/New_York'

[riotapi.limit]
[riotapi.limit.1]
MAX_REQUESTS = 20
REQUESTS_INTERVAL = 1

[riotapi.limit.2]
MAX_REQUESTS = 100
REQUESTS_INTERVAL = 120

[riotapi.routers]
[riotapi.routers.AccountV1]
ENTRY_SCALE=true
ENTRY_EXP_SCALE=false
DURATION_SCALE=false
DURATION_EXP_SCALE=false

[riotapi.routers.ChampionMasteryV4]
ENTRY_SCALE=true
ENTRY_EXP_SCALE=false
DURATION_SCALE=false
DURATION_EXP_SCALE=false

[riotapi.routers.ChampionV3]
ENTRY_SCALE=true
ENTRY_EXP_SCALE=false
DURATION_SCALE=false
DURATION_EXP_SCALE=false

[riotapi.routers.ClashV1]
ENTRY_SCALE=true
ENTRY_EXP_SCALE=false
DURATION_SCALE=false
DURATION_EXP_SCALE=false

[riotapi.routers.LolChallengesV1]
ENTRY_SCALE=true
ENTRY_EXP_SCALE=false
DURATION_SCALE=false
DURATION_EXP_SCALE=false

[riotapi.routers.MatchV5]
ENTRY_SCALE=true
ENTRY_EXP_SCALE=false
DURATION_SCALE=false
DURATION_EXP_SCALE=false




