[riotapi]

# The default value is 300 seconds means that update mechanism will be triggered every 5 minutes
REFRESH_RATE=300

[riotapi.key]
APIKEY="RGAPI-19b25ab4-3511-4eab-8546-80b7b530d809"
PARAM_NAME="api_key"
HEADER_NAME="X-Riot-Token"
PREFER_APPROACH="HEADER"

[riotapi.key.expiry_date]
# You can set either the token lifetime or program lifetime here as wished
# Note that when you have updates the value here, to make it effective, you must trigger one request to the RiotAPI
YEAR=2024
MONTH=5
DAY=31
HOUR=8
MINUTE=41
SECOND=0
TIMEZONE='America/New_York'

[riotapi.limit]
[riotapi.limit.global]
[riotapi.limit.global.1]
MAX_REQUESTS = 20
REQUESTS_INTERVAL = 1

[riotapi.limit.global.2]
MAX_REQUESTS = 100
REQUESTS_INTERVAL = 120


[riotapi.httpx_timeout]
# ALL=30
CONNECT=30
READ=30
WRITE=30
POOL=30


[riotapi.user]
# Default user
# PUUID="yAguDuygGSVyrXgyX0b04gcWweYxXyUuURwZI1p8RIuk-lc4iQV7VxL7h_hZK7mfQl4nBeqBPDXziA"
USERNAME="SlayerIchiruTake"
TAGLINE="5092"
REGION="VN2"
