[riotapi]

[riotapi.full.key]
# Development Key
APIKEY="RGAPI-711f241e-2bea-4b32-a7e2-ccb122fe2581"
PARAM_NAME="api_key"
HEADER_NAME="X-Riot-Token"
PREFER_APPROACH="HEADER"


[riotapi.lol.key]
APIKEY="RGAPI-711f241e-2bea-4b32-a7e2-ccb122fe2581"
PARAM_NAME="api_key"
HEADER_NAME="X-Riot-Token"
PREFER_APPROACH="HEADER"


[riotapi.lor.key]
APIKEY="RGAPI-711f241e-2bea-4b32-a7e2-ccb122fe2581"
PARAM_NAME="api_key"
HEADER_NAME="X-Riot-Token"
PREFER_APPROACH="HEADER"


[riotapi.tft.key]
APIKEY="RGAPI-711f241e-2bea-4b32-a7e2-ccb122fe2581"
PARAM_NAME="api_key"
HEADER_NAME="X-Riot-Token"
PREFER_APPROACH="HEADER"


[riotapi.val.key]
APIKEY="RGAPI-711f241e-2bea-4b32-a7e2-ccb122fe2581"
PARAM_NAME="api_key"
HEADER_NAME="X-Riot-Token"
PREFER_APPROACH="HEADER"


[riotapi.default]
# Default user
# PUUID="GG3JvY2K5hx6OKoy_f90Qyoh5mOLQVcmTc2nh0CFZroE6oZXUv33UQgR5H16cEz6pDByxH7nyCLWLQ"
# PUUID="yAguDuygGSVyrXgyX0b04gcWweYxXyUuURwZI1p8RIuk-lc4iQV7VxL7h_hZK7mfQl4nBeqBPDXziA"
# USERNAME="SlayerIchiruTake"
# TAGLINE="5092"
REGION="VN2"
