[riotapi]



[riotapi.default]
# The update mechanism will be triggered every 3 minutes
REFRESH_RATE=180
REGION="VN2"
CONTINENT="ASIA"
LOCALE="en_US"

[riotapi.default.httpx_timeout]
ALL=30
CONNECT=15
READ=15
WRITE=15
POOL=15



[riotapi.key]
APIKEY="RGAPI-711f241e-2bea-4b32-a7e2-ccb122fe2581"
PARAM_NAME="api_key"
HEADER_NAME="X-Riot-Token"
PREFER_APPROACH="HEADER"

[riotapi.expiry_date]
# You can set either the token lifetime or program lifetime here as wished
# Note that when you have updates the value here, to make it effective, you must trigger one request to the RiotAPI
YEAR=2024
MONTH=5
DAY=31
HOUR=8
MINUTE=41
SECOND=0
TIMEZONE='America/New_York'

[riotapi.limit]
[riotapi.limit.1]
MAX_REQUESTS = 20
REQUESTS_INTERVAL = 1

[riotapi.limit.2]
MAX_REQUESTS = 100
REQUESTS_INTERVAL = 120


[riotapi.httpx_timeout]
# ALL=30
CONNECT=30
READ=30
WRITE=30
POOL=30

